In [1]:
import pandas as pd

In [2]:
remaining = pd.read_csv('data/06_merged_results/remaining.csv')
match_true = pd.read_csv('data/06_merged_results/match_true.csv')

In [3]:
remaining

,Target Name,Target No.,preprocessed,First word,Top matched name for First word,Top matched No. for First word,Matched score for First word,Second word,Top matched name for Second word,Top matched No. for Second word,Matched score for Second word,Third word,Top matched name for Third word,Top matched No. for Third word,Matched score for Third word
0,1st Source Bank,22239,1st source bank,1st,21STORE,31840,91.0,1st source,URC,114704,86.6,1st source bank,Trust Bank,86763,88.4
1,21st Century Insurance Group,21615,21st century insurance group,21st,21STORE,31840,86.8,21st century,Century,117608,88.0,21st century insurance,Twenty First Century Insurance Group,61962,89.0
2,360 Capital Industrial Fund,3543,360 capital industrial fund,360,360 Capital REIT Units,80905,93.8,360 capital,360 Capital Group Stapled Units,80904,93.8,360 capital industrial,Capital Securities,115447,88.2
3,"AAG Holding Company, Inc.",20767,aag holding company,aag,AAG Holdings Company 7.5% Preferred,142184,94.0,aag holding,AAG Holdings Company 7.5% Preferred,142184,94.0,aag holding company,Yang Holding Company,69435,94.4
4,ABB Finance (Australia) Pty Limited,3541,abb finance (australia) pty,abb,ABB Grain (XETRA),309452,91.0,abb finance,B F,91340,84.0,abb finance (australia),Austral,177447,88.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,Zijin International Capital Company Limited,10605,zijin international capital company,zijin,Zijing International Financial Holdings,106069,94.6,zijin international,International,206505,90.8,zijin international capital,National Capital,75093,92.6
584,Zijin International Finance Company Limited,6661,zijin international finance company,zijin,Zijing International Financial Holdings,106069,95.6,zijin international,Zijing International Financial Holdings,106069,91.6,zijin international finance,National Finance,112023,92.6
585,Zions First National Bank,21458,zions first national bank,zions,Zions Capital Trust B Cap Securities,61896,91.8,zions first,First,186246,86.6,zions first national,National,10379,89.6
586,"Zoomlion HK SPV Co., Limited",10477,zoomlion hk spv,zoomlion,Lion,106810,88.4,zoomlion hk,Zoom,115081,88.4,zoomlion hk spv,Zoom,115081,88.4
587,Zur Rose Finance B.V.,16469,zur rose finance b.v.,zur,Zurich Insurance B,181624,92.4,zur rose,ZUR Rose (Frankfurt),276266,91.8,zur rose finance,ZUR Rose,116404,91.0

In [4]:
match_true

                              Target Name  Target No.   TRUE
0             360 Capital Industrial Fund        3543    NaN
1                   ABPA HOLDINGS LIMITED        9511    NaN
2                 AIG International, Inc.       21931    NaN
3                  ALD International S.A.        8556    NaN
4    AmBev International Finance Co. Ltd.        4155  AmBev
..                                    ...         ...    ...
583          CNOOC Finance (2003) Limited       25211  CNOOC
584          CNOOC Finance (2011) Limited       25231  CNOOC
585          CNOOC Finance (2012) Limited       25253  CNOOC
586          CNOOC Finance (2013) Limited       25290  CNOOC
587        CNOOC NEXEN FINANCE (2014) ULC        5294  CNOOC

[588 rows x 3 columns]

In [5]:
remaining_with_true = pd.merge(remaining, match_true, on=['Target Name', 'Target No.'])
remaining_with_true

,Target Name,Target No.,preprocessed,First word,Top matched name for First word,Top matched No. for First word,Matched score for First word,Second word,Top matched name for Second word,Top matched No. for Second word,Matched score for Second word,Third word,Top matched name for Third word,Top matched No. for Third word,Matched score for Third word,TRUE
0,1st Source Bank,22239,1st source bank,1st,21STORE,31840,91.0,1st source,URC,114704,86.6,1st source bank,Trust Bank,86763,88.4,1st source
1,21st Century Insurance Group,21615,21st century insurance group,21st,21STORE,31840,86.8,21st century,Century,117608,88.0,21st century insurance,Twenty First Century Insurance Group,61962,89.0,21st century
2,360 Capital Industrial Fund,3543,360 capital industrial fund,360,360 Capital REIT Units,80905,93.8,360 capital,360 Capital Group Stapled Units,80904,93.8,360 capital industrial,Capital Securities,115447,88.2,NaN
3,"AAG Holding Company, Inc.",20767,aag holding company,aag,AAG Holdings Company 7.5% Preferred,142184,94.0,aag holding,AAG Holdings Company 7.5% Preferred,142184,94.0,aag holding company,Yang Holding Company,69435,94.4,AAG
4,ABB Finance (Australia) Pty Limited,3541,abb finance (australia) pty,abb,ABB Grain (XETRA),309452,91.0,abb finance,B F,91340,84.0,abb finance (australia),Austral,177447,88.2,ABB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,Zijin International Capital Company Limited,10605,zijin international capital company,zijin,Zijing International Financial Holdings,106069,94.6,zijin international,International,206505,90.8,zijin international capital,National Capital,75093,92.6,Zijin Mining
584,Zijin International Finance Company Limited,6661,zijin international finance company,zijin,Zijing International Financial Holdings,106069,95.6,zijin international,Zijing International Financial Holdings,106069,91.6,zijin international finance,National Finance,112023,92.6,Zijin Mining
585,Zions First National Bank,21458,zions first national bank,zions,Zions Capital Trust B Cap Securities,61896,91.8,zions first,First,186246,86.6,zions first national,National,10379,89.6,NaN
586,"Zoomlion HK SPV Co., Limited",10477,zoomlion hk spv,zoomlion,Lion,106810,88.4,zoomlion hk,Zoom,115081,88.4,zoomlion hk spv,Zoom,115081,88.4,zoomlion
587,Zur Rose Finance B.V.,16469,zur rose finance b.v.,zur,Zurich Insurance B,181624,92.4,zur rose,ZUR Rose (Frankfurt),276266,91.8,zur rose finance,ZUR Rose,116404,91.0,Zur Rose

In [6]:
remaining_with_true.to_csv('data/06_merged_results/remaining.csv', index=False)