In [27]:
import pandas as pd

In [28]:
remaining = pd.read_csv('/home/haohang/research/text_matching/data/06_merged_results/merged_df.csv')
match_true = pd.read_excel('/home/haohang/research/text_matching/data/01_raw/test_run_with_true.xlsx')

In [29]:
remaining

,Target Name,Target No.,preprocessed,Focus Text,Matched Name 1,Matched No. 1,Matched Score 1,Matched Name 2,Matched No. 2,Matched Score 2,...,Matched Score 7,Matched Name 8,Matched No. 8,Matched Score 8,Matched Name 9,Matched No. 9,Matched Score 9,Matched Name 10,Matched No. 10,Matched Score 10
0,"AECOM GLOBAL II, LLC",24026,aecom global ii,aecom,Aecom Technology (XETRA),304295,99.52,Aecom,133456,99.50,...,99.33,OM Holdings,3117,99.24,OM,43231,99.24,AE,44716,99.24
1,AEGIS GAS (LPG) PRIVATE LIMITED,11750,aegis gas private,aegis,Aegis Realty,78574,99.62,Aegis Industries,62070,99.61,...,99.55,Aegis Brands (Frankfurt),260967,99.55,Aegis Assessments,69680,99.53,Aegis Assessments (Berlin),283993,99.53
2,AES Argentina Generacion S.A.,2810,aes argentina generacion,aes,AES China Generating A,69694,99.70,AES Tiete Energia On,150377,99.64,...,99.58,Caesars (Mexico) Entertainment,217005,99.58,Caesars (MIC) Entertainment,224047,99.58,Caesars (Frankfurt) Entertainment,261897,99.58
3,"AES CHANGUINOLA, S.A.",16760,aes changuinola,aes,Aesculap,14227,99.61,AES Chemunex,14225,99.59,...,99.53,Daesang Trading Company,33743,99.53,Aeso Holding,98378,99.52,Aeso Holding (Temp),164656,99.52
4,AES Chivor & CIA S.C.A. E.S.P.,7311,aes chivor & cia s.c.a. e.s.p.,aes,Caesars Acquisition Class A,59314,99.42,AES China Generating A,69694,99.42,...,99.40,AES Tiete Energia PN,150378,99.40,Aesthetic Medical (Frankfurt) International Ho...,267553,99.40,AES Tiete Energia ADR 1:1,202343,99.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,TIERS Corporate Bond-Backed Certificates Trust,21561,tiers corporate bond backed certificates,tiers,Citigroup Global Markets Holdings Tiers Trust ...,194127,99.53,Tiers Call Prin-Protected Assets Tiers 2006,80082,99.51,...,99.48,Structured Products Tiers Principal Protected ...,200824,99.46,Structured Products Tiers Principal Protected ...,200823,99.45,Structured Products Tiers 2003,200820,99.40
84,Wurth Finance International B.V.,16161,wurth b.v.,wurth,TH Group,30936,99.33,RT Group,50230,99.33,...,79.70,Rockworth NVDR,176155,79.70,Warthog,51572,79.67,Worthen Bank,69401,79.67
85,YPF ENERGIA ELECTRICA SOCIEDAD ANONIMA,2816,ypf energia electrica sociedad anonima,ypf,YPF Sociedad (Mexico) Anonima ADR Each 'D' 1:1,220928,99.53,Ypfb Transporte,80888,99.38,...,99.33,Repsol YPF (Stuttgart) Bonus Rights Code,281480,99.33,YPF S A (London),243315,99.31,Repsol YPF (Non-NASDAQ OTC) Bonus Rights,239426,99.30
86,Yinson Juniper Ltd,25390,yinson juniper,yinson,Yinson Holdings,107354,99.60,Company On,1218,99.25,...,85.47,Sony Bank Inc,30415,85.47,Sony (United Kingdom),50651,85.47,Sony Group,106094,85.47
87,adidas International Finance B.V.,16219,adidas b.v.,adidas,Adidas N (Milan),267489,99.74,Adidas,87384,99.71,...,99.71,Adidas (Bucharest),223673,99.71,Adidas (Swiss Stock Exchange),223674,99.71,Adidas (Swiss Stock Exchange),227017,99.71

In [30]:
match_true

                                       Target Name  Target No.          True
0                   Adani Welspun Exploration Ltd.       11951         ADANI
1                adidas International Finance B.V.       16219        Adidas
2            Aditya Birla Minacs Worldwide Limited       11639  Aditya Birla
3                             AECOM GLOBAL II, LLC       24026         Aecom
4                  AEGIS GAS (LPG) PRIVATE LIMITED       11750         Aegis
..                                             ...         ...           ...
83                                TD Capital Trust        4979   TD holdings
84  TIERS Corporate Bond-Backed Certificates Trust       21561         TIERS
85                Wurth Finance International B.V.       16161         Wurth
86                              Yinson Juniper Ltd       25390        Yinson
87          YPF ENERGIA ELECTRICA SOCIEDAD ANONIMA        2816           YPF

[88 rows x 3 columns]

In [31]:
remaining_with_true = pd.merge(remaining, match_true, on=['Target Name', 'Target No.'])
remaining_with_true

,Target Name,Target No.,preprocessed,Focus Text,Matched Name 1,Matched No. 1,Matched Score 1,Matched Name 2,Matched No. 2,Matched Score 2,...,Matched Name 8,Matched No. 8,Matched Score 8,Matched Name 9,Matched No. 9,Matched Score 9,Matched Name 10,Matched No. 10,Matched Score 10,True
0,"AECOM GLOBAL II, LLC",24026,aecom global ii,aecom,Aecom Technology (XETRA),304295,99.52,Aecom,133456,99.50,...,OM Holdings,3117,99.24,OM,43231,99.24,AE,44716,99.24,Aecom
1,AEGIS GAS (LPG) PRIVATE LIMITED,11750,aegis gas private,aegis,Aegis Realty,78574,99.62,Aegis Industries,62070,99.61,...,Aegis Brands (Frankfurt),260967,99.55,Aegis Assessments,69680,99.53,Aegis Assessments (Berlin),283993,99.53,Aegis
2,AES Argentina Generacion S.A.,2810,aes argentina generacion,aes,AES China Generating A,69694,99.70,AES Tiete Energia On,150377,99.64,...,Caesars (Mexico) Entertainment,217005,99.58,Caesars (MIC) Entertainment,224047,99.58,Caesars (Frankfurt) Entertainment,261897,99.58,AES
3,"AES CHANGUINOLA, S.A.",16760,aes changuinola,aes,Aesculap,14227,99.61,AES Chemunex,14225,99.59,...,Daesang Trading Company,33743,99.53,Aeso Holding,98378,99.52,Aeso Holding (Temp),164656,99.52,AES
4,AES Chivor & CIA S.C.A. E.S.P.,7311,aes chivor & cia s.c.a. e.s.p.,aes,Caesars Acquisition Class A,59314,99.42,AES China Generating A,69694,99.42,...,AES Tiete Energia PN,150378,99.40,Aesthetic Medical (Frankfurt) International Ho...,267553,99.40,AES Tiete Energia ADR 1:1,202343,99.40,AES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,TIERS Corporate Bond-Backed Certificates Trust,21561,tiers corporate bond backed certificates,tiers,Citigroup Global Markets Holdings Tiers Trust ...,194127,99.53,Tiers Call Prin-Protected Assets Tiers 2006,80082,99.51,...,Structured Products Tiers Principal Protected ...,200824,99.46,Structured Products Tiers Principal Protected ...,200823,99.45,Structured Products Tiers 2003,200820,99.40,TIERS
84,Wurth Finance International B.V.,16161,wurth b.v.,wurth,TH Group,30936,99.33,RT Group,50230,99.33,...,Rockworth NVDR,176155,79.70,Warthog,51572,79.67,Worthen Bank,69401,79.67,Wurth
85,YPF ENERGIA ELECTRICA SOCIEDAD ANONIMA,2816,ypf energia electrica sociedad anonima,ypf,YPF Sociedad (Mexico) Anonima ADR Each 'D' 1:1,220928,99.53,Ypfb Transporte,80888,99.38,...,Repsol YPF (Stuttgart) Bonus Rights Code,281480,99.33,YPF S A (London),243315,99.31,Repsol YPF (Non-NASDAQ OTC) Bonus Rights,239426,99.30,YPF
86,Yinson Juniper Ltd,25390,yinson juniper,yinson,Yinson Holdings,107354,99.60,Company On,1218,99.25,...,Sony Bank Inc,30415,85.47,Sony (United Kingdom),50651,85.47,Sony Group,106094,85.47,Yinson
87,adidas International Finance B.V.,16219,adidas b.v.,adidas,Adidas N (Milan),267489,99.74,Adidas,87384,99.71,...,Adidas (Bucharest),223673,99.71,Adidas (Swiss Stock Exchange),223674,99.71,Adidas (Swiss Stock Exchange),227017,99.71,Adidas

In [32]:
remaining_with_true.to_csv('data/06_merged_results/0.99.csv', index=False)